/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wzw_server_DiffUtils */

#ifndef _Included_com_wzw_server_DiffUtils
#define _Included_com_wzw_server_DiffUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wzw_server_DiffUtils
 * Method:    genDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wzw_server_DiffUtils_genDiff
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
