/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wzw_server_PatchUtils */

#ifndef _Included_com_wzw_server_PatchUtils
#define _Included_com_wzw_server_PatchUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wzw_server_PatchUtils
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wzw_server_PatchUtils_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
